# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BUILD_CONTAINER=jupyter/datascience-notebook
FROM $BUILD_CONTAINER

LABEL maintainer="Graeme Seaton <graemes@github>"

# Set when building on Travis so that certain long-running build steps can
# be skipped to shorten build time.
ARG TEST_ONLY_BUILD

#ENV CUDNN_VERSION 7.6.2.24
USER root

# Install Tensorflow
#RUN apt-get update && apt-get install -y --no-install-recommends \
#            libcudnn7=$CUDNN_VERSION-1+cuda10.1 \
#            libcudnn7-dev=$CUDNN_VERSION-1+cuda10.1 && \
#    apt-mark hold libcudnn7 && \
#    rm -rf /var/lib/apt/lists/*

## Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID

##RUN conda install --quiet --yes \
##    'tensorflow-gpu=2.3.0' \
##    'keras=2.2*' \
##    'watermark=1.*' \
##    numba cudatoolkit && \
##    conda clean --all -f -y && \
##    npm cache clean --force 

##    numba cudatoolkit pyculib && \
##    jupyter labextension install @jupyterlab/git && \
##    jupyter labextension install @jupyterlab/toc && \

##RUN conda install -c defaults -c gpuopenanalytics/label/dev -c conda-forge pygdf && \
##    rm -rf /home/$NB_USER/.cache/yarn && \
##    fix-permissions $CONDA_DIR && \
##    fix-permissions /home/$NB_USER

# Install Tensorflow
 RUN pip install --quiet --no-cache-dir \
     'tensorflow-gpu==2.3.0' && \
     fix-permissions "${CONDA_DIR}" && \
     fix-permissions "/home/${NB_USER}"
