#!/bin/bash
# Define the base registry and other parameters for building Docker images.

BASE_REGISTRY="registry.graemes.cloud/jupyter/stacks"
BASE_REGISTRY_CLOUD="registry.graemes.cloud/jupyter/stacks"
REGISTRY="registry.graemes.cloud"
OWNER="jupyter/stacks"

UBUNTU_VERSION="24.04"

