#!/bin/bash
# This script sets up the build parameters for the Docker stacks foundation.
# It sources common build parameters and defines specific variables for this project.

source ${HOME}/build/tools/build-params
source ../build-params

BASE_REPOSITORY="docker-stacks-foundation"

ROOT_IMAGE="registry.graemes.cloud/graemes/ubuntubuild:${UBUNTU_VERSION}"
GPU_ROOT_IMAGE="registry.graemes.cloud/nvidia/cuda/devel:${CUDA_VERSION}-ubuntu${UBUNTU_VERSION}"

BASE_OUTPUT="${BASE_REGISTRY}/${BASE_REPOSITORY}"
BASE_OUTPUT_CLOUD="${BASE_REGISTRY_CLOUD}/${BASE_REPOSITORY}"

