#!/bin/bash
# This script sets up the build parameters for the Docker stacks foundation.
# It sources common build parameters and defines specific variables for this project.

source ../build-params

BASE_IMAGE="pyspark-notebook"
BASE_REPOSITORY="all-spark-notebook"
