#!/bin/bash

# Created by argbash-init v2.10.0
# Rearrange the order of options below according to what you would like to see in the help message.
# ARG_POSITIONAL_SINGLE([container-type],[container-type: only use 'gpu'],[""])
# ARG_DEFAULTS_POS([])
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_container_type=""
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "<The general help message of my script>"
	printf 'Usage: %s [-h|--help] [<container-type>]\n' "$0"
	printf '\t%s\n' "<container-type>: container-type: only use 'gpu' (default: '""')"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 0 and 1, but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_container_type "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


# vvv  PLACE YOUR CODE HERE  vvv

# Define variables
CONTAINER_TYPE=${_arg_container_type}

source ./build-params

# List of tags to apply
TAGS=("latest" "ubuntu24.04")

# Validate TYPE parameter
if [ -n "$CONTAINER_TYPE" ] && [ "$CONTAINER_TYPE" != "gpu" ]; then
    echo "Invalid CONTAINER_TYPE specified. Only 'gpu' or none is allowed."
    exit 1
fi

if [ "$CONTAINER_TYPE" = "gpu" ]; then
	ROOT_IMAGE=${GPU_ROOT_IMAGE}
fi

echo "Base Container: ${ROOT_IMAGE}"
echo "Base Output: ${BASE_OUTPUT}"
echo "Base Output - cloud: ${BASE_OUTPUT_CLOUD}"

docker pull ${ROOT_IMAGE}

# Build the Docker image and tag it with multiple tags
for TAG in "${TAGS[@]}"; do
    if  [ -n "$CONTAINER_TYPE" ] ; then
        TAG_NAME="${CONTAINER_TYPE}-${TAG}"
    else
        TAG_NAME="${TAG}"
    fi

	echo "Image: ${BASE_OUTPUT}:${TAG_NAME}"
	echo "Image - cloud: ${BASE_OUTPUT_CLOUD}:${TAG_NAME}"

    docker buildx build . \
    	--platform linux/amd64 \
		--build-arg ROOT_IMAGE=${ROOT_IMAGE} \
		-t ${BASE_OUTPUT}:${TAG_NAME} \
		-t ${BASE_OUTPUT_CLOUD}:${TAG_NAME} \
		--push
done

echo "Docker images pushed successfully!"

# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^

# ] <-- needed because of Argbash
